name: dunelegacy-com
region: nyc

# Static website service (metaserver moved to dedicated Droplet)
static_sites:
  - name: website
    source_dir: website
    github:
      repo: svan058/dunelegacy.com
      branch: main
      deploy_on_push: true
    catchall_document: index.html

# Custom domain (configure after app is created)
domains:
  - domain: dunelegacy.com
    type: PRIMARY
  - domain: www.dunelegacy.com
    type: ALIAS

